import re
import os

INPUT_FILE_PATH = 'C:\\Users\\' + os.getlogin() + '\\Documents\\Paradox Interactive\\Hearts of Iron IV\\mod\\Kaiserreich Dev Build\\interface\\kaiserreich\\technology_icons_tanks.gfx'
OUTPUT_FILE_PATH = 'C:\\Users\\' + os.getlogin() + '\\Documents\\Paradox Interactive\\Hearts of Iron IV\\mod\\Kaiserreich Dev Build\\interface\\kaiserreich\\technology_icons_tank_chassis.gfx'
HEADER_STR = "### This file is autogenerated. Don't edit it manually. Content is sorted alphabetically. By Pelmen323\n"
INPUT_LIST = [
    ['gwtank_medium', 'gwtank_chassis_medium'],
    ['gwtank_medium', 'light_tank_chassis_0_medium'],
    ['basic_light_tank_medium', 'basic_light_tank_chassis_medium'],
    ['improved_light_tank_medium', 'improved_light_tank_chassis_medium'],
    ['advanced_light_tank_medium', 'advanced_light_tank_chassis_medium'],
    ['early_medium_tank_medium', 'medium_tank_chassis_0_medium'],
    ['basic_medium_tank_medium', 'basic_medium_tank_chassis_medium'],
    ['improved_medium_tank_medium', 'improved_medium_tank_chassis_medium'],
    ['advanced_medium_tank_medium', 'advanced_medium_tank_chassis_medium'],
    ['early_heavy_tank_medium', 'heavy_tank_chassis_0_medium'],
    ['basic_heavy_tank_medium', 'basic_heavy_tank_chassis_medium'],
    ['improved_heavy_tank_medium', 'improved_heavy_tank_chassis_medium'],
    ['advanced_heavy_tank_medium', 'advanced_heavy_tank_chassis_medium'],
    ['super_heavy_tank_medium', 'super_heavy_tank_chassis_medium'],
    ['land_cruiser_armor_medium', 'land_cruiser_chassis_medium'],
    ['main_battle_tank_medium', 'main_battle_tank_chassis_medium'],
    ['amphibious_tank_medium', 'amphibious_tank_chassis_medium']
]


def main(input_list: list[str, str]):
    '''
    This script autogenerates chassis icons based on tank icons
    Input - List
    Input[0] - chassis icon
    Input[1] - tank icon
    Script generates chassis icons for all tags that have relevant tank icons
    '''
    output_list = []

    with open(INPUT_FILE_PATH, 'r', encoding='utf-8') as text_file:
        input_file = text_file.read()

    for item in input_list:
        i = item[0]
        chassis = item[1]
        tank_icon_pattern = 'GFX_..._' + i
        tank_tech_icons = re.findall(tank_icon_pattern, input_file)

        for tank_icon in tank_tech_icons:
            tag = re.findall(r'GFX_(...)_', tank_icon)[0]
            tank_icon_path = re.findall(tank_icon + '.*?\n.*?texturefile.*?=.*?"(.*?)"', input_file)[0]
            output_str = '\tSpriteType = {\n\t\tname = "GFX_' + tag + '_' + chassis + '"\n\t\ttexturefile = "' + tank_icon_path + '"\n\t}\n'
            output_list.append(output_str)

    with open(OUTPUT_FILE_PATH, 'w', encoding='utf-8') as text_file_write:
        output_list = sorted(output_list)
        output_file = HEADER_STR + 'spriteTypes = {\n' + ''.join(output_list) + '}\n'
        text_file_write.write(output_file)


if __name__ == '__main__':
    main(INPUT_LIST)
