inputstr = """
 ENG_CAS_equipment_1: "Hawker Hind"
 ENG_CAS_equipment_1_short: "Hind"
 ENG_cv_CAS_equipment_1: "Hawker Hind"
 ENG_cv_CAS_equipment_1_short: "Hind"
 ENG_CAS_equipment_2: "Hawker Typhoon"
 ENG_CAS_equipment_2_short: "Typhoon"
 ENG_cv_CAS_equipment_2: "Hawker Firefly"
 ENG_cv_CAS_equipment_2_short: "Firefly"
 ENG_CAS_equipment_3: "Hawker Tempest"
 ENG_CAS_equipment_3_short: "Tempest"
 ENG_cv_CAS_equipment_3: "Hawker Brigand"
 ENG_cv_CAS_equipment_3_short: "Brigand"

 ENG_fighter_equipment_0: "Hawker Fury"
 ENG_fighter_equipment_0_short: "Fury"
 ENG_cv_fighter_equipment_0: "Hawker Nimrod"
 ENG_cv_fighter_equipment_0_short: "Nimrod"
 ENG_fighter_equipment_1: "Hawker Hurricane"
 ENG_fighter_equipment_1_short: "Hurricane"
 ENG_cv_fighter_equipment_1: "Hawker Sea Hurricane"
 ENG_cv_fighter_equipment_1_short: "Sea Hurricane"
 ENG_fighter_equipment_2: "Supermarine Spitfire"
 ENG_fighter_equipment_2_short: "Spitfire"
 ENG_cv_fighter_equipment_2: "Hawker Sea Spitfire"
 ENG_cv_fighter_equipment_2_short: "Sea Spitfire"
 ENG_fighter_equipment_3: "Supermarine Spiteful"
 ENG_fighter_equipment_3_short: "Spiteful"
 ENG_cv_fighter_equipment_3: "Hawker Sea Spiteful"
 ENG_cv_fighter_equipment_3_short: "Sea Spiteful"
 ENG_jet_fighter_equipment_1: "de Havilland Vampire"
 ENG_jet_fighter_equipment_1_short: "Vampire"
 ENG_jet_fighter_equipment_2: "Hawker Star"
 ENG_small_plane_airframe_5: "Hawker Star"
 ENG_jet_fighter_equipment_2_short: "Star"
 ENG_small_plane_airframe_5_short: "Star"

 ENG_nav_bomber_equipment_1: "Blackburn Baffin"
 ENG_nav_bomber_equipment_1_short: "Baffin"
 ENG_cv_nav_bomber_equipment_1: "Blackburn Swordfish"
 ENG_cv_nav_bomber_equipment_1_short: "Swordfish"
 ENG_nav_bomber_equipment_2: "Blackburn Skua"
 ENG_nav_bomber_equipment_2_short: "Skua"
 ENG_cv_nav_bomber_equipment_2: "Blackburn Albacore"
 ENG_cv_nav_bomber_equipment_2_short: "Albacore"
 ENG_nav_bomber_equipment_3: "Blackburn Firebrand"
 ENG_nav_bomber_equipment_3_short: "Firebrand"
 ENG_cv_nav_bomber_equipment_3: "Blackburn Barracuda"
 ENG_cv_nav_bomber_equipment_3_short: "Barracuda"

 ENG_heavy_fighter_equipment_1: "Boulton-Paul Defiant"
 ENG_heavy_fighter_equipment_1_short: "Defiant"
 ENG_heavy_fighter_equipment_2: "Westland Whirlwind"
 ENG_heavy_fighter_equipment_2_short: "Whirlwind"
 ENG_heavy_fighter_equipment_3: "de Havilland Hornet"
 ENG_heavy_fighter_equipment_3_short: "Hornet"

 ENG_tac_bomber_equipment_0: "Boulton-Paul Overstrand"
 ENG_tac_bomber_equipment_0_short: "Overstrand"
 ENG_tac_bomber_equipment_1: "Handley-Page Hampden"
 ENG_tac_bomber_equipment_1_short: "Hampden"
 ENG_tac_bomber_equipment_2: "Armstrong-Whitworth Albermale"
 ENG_tac_bomber_equipment_2_short: "Albermale"
 ENG_tac_bomber_equipment_3: "de Havilland Mosquito"
 ENG_tac_bomber_equipment_3_short: "Mosquito"
 ENG_jet_tac_bomber_equipment_1: "de Havilland Venom"
 ENG_jet_tac_bomber_equipment_1_short: "Venom"
 ENG_jet_tac_bomber_equipment_2: "English Electric Lincoln"
 ENG_jet_tac_bomber_equipment_2_short: "Lincoln"

 ENG_strat_bomber_equipment_1: "Armstrong-Whitworth Whitley"
 ENG_strat_bomber_equipment_1_short: "Whitley"
 ENG_strat_bomber_equipment_2: "Handley-Page Calderdale"
 ENG_strat_bomber_equipment_2_short: "Calderdale"
 ENG_strat_bomber_equipment_3: "Short Stirling"
 ENG_strat_bomber_equipment_3_short: "Stirling"
 ENG_jet_strat_bomber_equipment_1: "Hawker Courageous"
 ENG_jet_strat_bomber_equipment_1_short: "Courageous"

 ENG_scout_plane_equipment_1: "Westland Lysander"
 ENG_scout_plane_equipment_1_short: "Lysander"
 ENG_scout_plane_equipment_2: "Supermarine Spitfire PR"
 ENG_scout_plane_equipment_2_short: "Spitfire PR"
"""

x = []
for i in inputstr.split('\n'):
    if '"' in i:
        key, to_replace = i.strip().split(':')
        replaced_line = i.replace(to_replace, ' "$'+key+'$"')
        x.append(replaced_line)

for i in x:
    print(i)